using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using PetManager.Domain.Models;

namespace PetManager.Infrastructure;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    public DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("users");

            // Id is generated by the application (Guid), not the database
            entity.HasKey(u => u.Id);
            entity.Property(u => u.Id).ValueGeneratedNever();

            entity.Property(u => u.Username)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("username");

            // Password stored as bcrypt hash (application responsibility)
            entity.Property(u => u.PasswordHash)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("password_hash");

            entity.Property(u => u.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");

            entity.Property(u => u.Email)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("email");
            entity.HasIndex(u => u.Email).IsUnique();

            entity.Property(u => u.Cellphone)
                .HasMaxLength(50)
                .HasColumnName("cellphone");

            entity.Property(u => u.Document)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("document");
            entity.HasIndex(u => u.Document).IsUnique();

            entity.Property(u => u.Role)
                .IsRequired()
                .HasColumnName("role");

            // Let PostgreSQL set creation timestamp by default
            entity.Property(u => u.CreatedAt)
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()")
                .ValueGeneratedOnAdd();

            // UpdatedAt is managed by the application on modifications
            entity.Property(u => u.UpdatedAt)
                .HasColumnName("updated_at");

            entity.Property(u => u.Status)
                .IsRequired()
                .HasColumnName("status");
        });
    }
}
