using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using PetManager.Domain.Models;

namespace PetManager.Infrastructure;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    public DbSet<User> Users { get; set; }
    public DbSet<ApiKey> ApiKeys { get; set; }
    public DbSet<RefreshToken> RefreshTokens { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("users");

            // Id is generated by the application (Guid), not the database
            entity.HasKey(u => u.Id);
            entity.Property(u => u.Id).ValueGeneratedNever();

            entity.Property(u => u.Username)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("username");

            // Password stored as bcrypt hash (application responsibility)
            entity.Property(u => u.PasswordHash)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("password_hash");

            entity.Property(u => u.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");

            entity.Property(u => u.Email)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("email");
            entity.HasIndex(u => u.Email).IsUnique();

            entity.Property(u => u.Cellphone)
                .HasMaxLength(50)
                .HasColumnName("cellphone");

            entity.Property(u => u.Document)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("document");
            entity.HasIndex(u => u.Document).IsUnique();

            entity.Property(u => u.Role)
                .IsRequired()
                .HasColumnName("role");

            // Let PostgreSQL set creation timestamp by default
            entity.Property(u => u.CreatedAt)
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()")
                .ValueGeneratedOnAdd();

            // UpdatedAt is managed by the application on modifications
            entity.Property(u => u.UpdatedAt)
                .HasColumnName("updated_at");

            entity.Property(u => u.Status)
                .IsRequired()
                .HasColumnName("status");
        });

        modelBuilder.Entity<ApiKey>(entity =>
        {
            entity.ToTable("api_keys");

            entity.HasKey(a => a.Id);
            entity.Property(a => a.Id).ValueGeneratedNever();

            entity.Property(a => a.Key)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("key");
            entity.HasIndex(a => a.Key).IsUnique();

            entity.Property(a => a.Description)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("description");

            entity.Property(a => a.CreatedAt)
                .IsRequired()
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()")
                .ValueGeneratedOnAdd();

            entity.Property(a => a.IsActive)
                .IsRequired()
                .HasColumnName("is_active")
                .HasDefaultValue(true);
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.ToTable("refresh_tokens");

            entity.HasKey(r => r.Id);
            entity.Property(r => r.Id).ValueGeneratedNever();

            entity.Property(r => r.ApiKeyId)
                .HasColumnName("api_key_id");

            entity.Property(r => r.UserId)
                .HasColumnName("user_id");

            entity.Property(r => r.Token)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("token");

            entity.Property(r => r.CreatedAt)
                .IsRequired()
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()")
                .ValueGeneratedOnAdd();

            entity.Property(r => r.ExpiresAt)
                .IsRequired()
                .HasColumnName("expires_at");

            entity.Property(r => r.IsRevoked)
                .IsRequired()
                .HasColumnName("is_revoked")
                .HasDefaultValue(false);

            // Foreign keys - both are optional (either ApiKeyId or UserId must be set)
            entity.HasOne(r => r.ApiKey)
                .WithMany()
                .HasForeignKey(r => r.ApiKeyId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired(false);

            entity.HasOne(r => r.User)
                .WithMany()
                .HasForeignKey(r => r.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired(false);

            entity.HasIndex(r => r.Token).IsUnique();
        });
    }
}
